"""Initial schema

Revision ID: 28c1e694661e
Revises: 
Create Date: 2025-04-04 11:37:26.424471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c1e694661e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oks',
    sa.Column('УИН', sa.String(), nullable=False),
    sa.Column('Класс', sa.String(), nullable=True),
    sa.Column('Подкласс 1', sa.String(), nullable=True),
    sa.Column('Подкласс 2', sa.String(), nullable=True),
    sa.Column('Подкласс 3', sa.String(), nullable=True),
    sa.Column('Тип (%%)', sa.String(), nullable=True),
    sa.Column('Наименование', sa.String(), nullable=True),
    sa.Column('Определение', sa.Text(), nullable=True),
    sa.Column('Источник', sa.Text(), nullable=True),
    sa.Column('Критерии определения подклассов', sa.Text(), nullable=True),
    sa.Column('Технико-экономические показатели\n<Prp>', sa.Text(), nullable=True),
    sa.Column('Код соответствующего ОКС (группы ОКС) по классификатору ОКС ГГЭ', sa.String(), nullable=True),
    sa.Column('Код соответствующего ОКС по классификатору МССК', sa.String(), nullable=True),
    sa.Column('Код соответствующего ОКС по КТИМ ОАО "РЖД"', sa.String(), nullable=True),
    sa.Column('Примечания', sa.Text(), nullable=True),
    sa.Column('Синонимы', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('УИН')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oks')
    # ### end Alembic commands ###
